# ==========================
# DEV = "PROD local"
# ==========================

# Actuator: lo mínimo para prod-like
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Devtools OFF
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Logging prod-like
logging.level.com.mtripode.jobapp=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

# SQL OFF
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Cache
spring.cache.type=redis

# Kafka (dev -> dev)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:jobapp-kafka-dev:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
jobapp.kafka.topic.application-events=${JOBAPP_KAFKA_TOPIC_APPLICATION_EVENTS:job.application.events}
