# ==========================
# LOCAL = DEV real
# ==========================

# Actuator abierto para debug
management.endpoints.web.exposure.include=health,info,metrics,env,loggers,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

# Devtools ON
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.exclude=static/**,public/**,templates/**

# Logging más verboso
logging.level.com.mtripode.jobapp=DEBUG
logging.level.com.mtripode.jobapp.logging=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# SQL visible en dev real
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache
spring.cache.type=redis

# Kafka (local -> local)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:jobapp-kafka-local:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
jobapp.kafka.topic.application-events=${JOBAPP_KAFKA_TOPIC_APPLICATION_EVENTS:job.application.events}
