apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: jobapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          args:
            - --default-authentication-plugin=mysql_native_password
          startupProbe:
            tcpSocket:
              port: 3306
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
