apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: jobapp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: jobapp_db
  MYSQL_USER: jobuser
  MYSQL_PASSWORD: jobpass