apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: jobapp
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_CACHE_TYPE: "simple"
  MANAGEMENT_HEALTH_REDIS_ENABLED: "false"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/jobapp_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

  NOTE_SERVICE_URL: "http://mongodb-backend:8080/notes"
